import React, { useEffect, useState } from 'react';
import somaBackend from '../../somaBackend.js';

const box = theme => ({ padding:18, border:`1px solid ${theme.hair}`, borderRadius:6, background:'oklch(0.13 0.012 55 / .9)' });
const button = theme => ({ padding:'7px 10px', border:`1px solid ${theme.hair}`, borderRadius:3, background:'transparent', color:theme.textDim, cursor:'pointer', fontSize:9, letterSpacing:'.12em', textTransform:'uppercase' });
const cash = value => `$${Math.round(Number(value) || 0).toLocaleString()}`;
const numericInput = theme => ({ width:'100%', boxSizing:'border-box', padding:'7px 8px', background:'oklch(0.10 0.01 50)', border:`1px solid ${theme.hair}`, borderRadius:3, color:theme.text, fontSize:10 });

function MarketModel({ job, setJob, theme, onError }) {
  const [market, setMarket] = useState(job.marketModel?.assumptions || {});
  const [tiers, setTiers] = useState(job.pricingModel?.tiers || []);
  const [usePricingMix, setUsePricingMix] = useState(false);
  const [preview, setPreview] = useState(null);
  const [busy, setBusy] = useState('');
  useEffect(() => { setMarket(job.marketModel?.assumptions || {}); setTiers(job.pricingModel?.tiers || []); }, [job.id, job.marketModel?.calculatedAt, job.pricingModel?.calculatedAt]);
  useEffect(() => {
    let active = true;
    const timer = setTimeout(() => somaBackend.previewBusinessPlanModel(job.id, { marketAssumptions:market, pricingTiers:tiers, usePricingMix }).then(result => { if (active) setPreview(result.preview); }).catch(() => {}), 400);
    return () => { active = false; clearTimeout(timer); };
  }, [job.id, market, tiers, usePricingMix]);
  const setMarketValue = (key, value) => setMarket(current => ({ ...current, [key]:value }));
  const setTierValue = (index, key, value) => setTiers(current => current.map((tier, tierIndex) => tierIndex === index ? { ...tier, [key]:value } : tier));
  const save = async () => { setBusy('save'); try { const result = await somaBackend.updateBusinessPlanModel(job.id, { marketAssumptions:market, pricingTiers:tiers, usePricingMix }); setJob(result.job); } catch (error) { onError(error.message); } finally { setBusy(''); } };
  const recalibrate = async () => { setBusy('research'); try { const result = await somaBackend.recalibrateBusinessPlanModel(job.id, 'Recalibrate market sizing and pricing using the strongest current evidence. Preserve unsupported inputs as assumptions.'); setJob(result.job); } catch (error) { onError(error.message); } finally { setBusy(''); } };
  const decide = async apply => { const proposal = job.modelProposal; if (!proposal) return; setBusy(apply ? 'apply' : 'discard'); try { const result = apply ? await somaBackend.applyBusinessPlanModelProposal(job.id, proposal.id) : await somaBackend.discardBusinessPlanModelProposal(job.id, proposal.id); setJob(result.job); } catch (error) { onError(error.message); } finally { setBusy(''); } };
  const sizing = preview?.marketModel || job.marketModel || {}; const pricing = preview?.pricingModel || job.pricingModel || {}; const financial = preview?.financialModel || job.financialModel;
  const marketFields = [['totalPotentialCustomers','Potential customers'],['annualSpendPerCustomer','Annual spend / customer'],['serviceableGeographyPct','Serviceable geography %'],['targetSegmentPct','Target segment %'],['year3ObtainableSharePct','Year-3 share %'],['annualMarketGrowthPct','Annual market growth %']];
  const tierFields = [['price','Price'],['materialCost','Materials'],['laborCost','Labor'],['fulfillmentCost','Fulfillment'],['commissionPct','Commission %'],['warrantyReservePct','Reserve %'],['monthlyVolume','Volume']];
  return <div style={{ display:'grid', gap:12 }}>
    <section style={box(theme)}><div style={{ display:'flex', justifyContent:'space-between', gap:16, alignItems:'start' }}><div><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.18em', textTransform:'uppercase' }}>auditable market sizing</div><p style={{ color:theme.textMute, fontSize:10, lineHeight:1.55 }}>Top-down market bounds are reconciled against the deterministic year-three bottom-up model. These are assumptions until linked to evidence.</p></div><div style={{ textAlign:'right' }}><div style={{ color:theme.ember, fontSize:24 }}>{sizing.confidence?.score || 0}%</div><div style={{ color:theme.textMute, fontSize:9 }}>{sizing.confidence?.label}</div></div></div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(4,minmax(0,1fr))', gap:8, marginTop:14 }}>{[['TAM',sizing.tam],['SAM',sizing.sam],['3-year SOM',sizing.som],['Bottom-up Y3',sizing.bottomUpYear3]].map(([label,value]) => <div key={label} style={{ padding:12, border:`1px solid ${theme.hair}`, borderRadius:4 }}><div style={{ color:theme.textMute, fontSize:9, textTransform:'uppercase' }}>{label}</div><div style={{ color:theme.text, fontSize:18, marginTop:5 }}>{cash(value)}</div></div>)}</div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(3,minmax(0,1fr))', gap:10, marginTop:14 }}>{marketFields.map(([key,label]) => <label key={key} style={{ color:theme.textMute, fontSize:9, textTransform:'uppercase' }}>{label}<input type="number" value={market[key] ?? ''} onChange={event => setMarketValue(key,event.target.value)} style={{ ...numericInput(theme), display:'block', marginTop:5 }} />{['totalPotentialCustomers','annualSpendPerCustomer','annualMarketGrowthPct'].includes(key) && <input value={(market.sourceRefs?.[key] || []).join(', ')} onChange={event => setMarket(current => ({ ...current, sourceRefs:{ ...(current.sourceRefs || {}), [key]:event.target.value.split(',').map(value => value.trim()).filter(Boolean) } }))} placeholder="Evidence IDs, e.g. S1, S4" style={{ ...numericInput(theme), display:'block', marginTop:4, color:theme.ember }} />}</label>)}</div>
      {(sizing.warnings || []).map(warning => <div key={warning} style={{ marginTop:7, color:'oklch(0.78 0.1 60)', fontSize:10 }}>⚠ {warning}</div>)}
    </section>
    <section style={box(theme)}><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.18em', textTransform:'uppercase' }}>pricing tiers and unit economics</div><div style={{ overflowX:'auto', marginTop:12 }}><table style={{ width:'100%', minWidth:860, borderCollapse:'collapse' }}><thead><tr><th style={{ textAlign:'left', color:theme.textMute, fontSize:9 }}>TIER</th>{tierFields.map(([,label]) => <th key={label} style={{ textAlign:'left', color:theme.textMute, fontSize:9 }}>{label.toUpperCase()}</th>)}<th style={{ color:theme.textMute, fontSize:9 }}>MARGIN</th><th style={{ color:theme.textMute, fontSize:9 }}>CONTRIBUTION</th></tr></thead><tbody>{tiers.map((tier,index) => <tr key={tier.id}><td style={{ padding:'6px 5px 6px 0' }}><input value={tier.name} onChange={event => setTierValue(index,'name',event.target.value)} style={{ ...numericInput(theme), minWidth:120 }} /></td>{tierFields.map(([key]) => <td key={key} style={{ padding:5 }}><input type="number" value={tier[key] ?? ''} onChange={event => setTierValue(index,key,event.target.value)} style={{ ...numericInput(theme), minWidth:76 }} /></td>)}<td style={{ color:theme.ember, fontSize:10, textAlign:'center' }}>{pricing.tiers?.[index]?.grossMarginPct || 0}%</td><td style={{ color:theme.text, fontSize:10, textAlign:'center' }}>{cash(pricing.tiers?.[index]?.contributionProfit)}</td></tr>)}</tbody></table></div>
      <div style={{ display:'flex', flexWrap:'wrap', gap:16, marginTop:12, color:theme.textDim, fontSize:10 }}><span>Weighted price {cash(pricing.weightedAveragePrice)}</span><span>LTV {cash(pricing.ltv)}</span><span>CAC {cash(pricing.customerAcquisitionCost)}</span><span>LTV:CAC {pricing.ltvCacRatio || 'n/a'}×</span><span>Payback {pricing.cacPaybackMonths || 'n/a'} months</span></div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(3,minmax(0,1fr))', gap:7, marginTop:12 }}>{(financial?.scenarios?.base?.annual || []).map(year => <div key={year.year} style={{ padding:10, border:`1px solid ${theme.hair}`, borderRadius:3 }}><div style={{ color:theme.textMute, fontSize:9 }}>LIVE YEAR {year.year}</div><div style={{ color:theme.text, marginTop:4, fontSize:12 }}>{cash(year.revenue)} revenue</div><div style={{ color:year.operatingProfit >= 0 ? 'oklch(0.74 0.10 145)' : 'oklch(0.74 0.10 25)', marginTop:3, fontSize:10 }}>{cash(year.operatingProfit)} operating profit</div></div>)}</div>
    </section>
    {job.modelProposal?.status === 'proposed' && <section style={{ ...box(theme), borderColor:theme.ember }}><div style={{ color:theme.ember, fontSize:10, textTransform:'uppercase' }}>SOMA recalibration proposal · not applied</div><p style={{ color:theme.textDim, fontSize:11 }}>{job.modelProposal.summary}</p>{job.modelProposal.unresolved?.map(item => <div key={item} style={{ color:theme.textMute, fontSize:10, marginTop:5 }}>Unresolved: {item}</div>)}<div style={{ display:'flex', gap:7, marginTop:12 }}><button onClick={() => decide(false)} style={button(theme)}>keep current</button><button onClick={() => decide(true)} style={{ ...button(theme), background:theme.ember, color:theme.voidDeep, borderColor:theme.ember }}>apply proposal</button></div></section>}
    <div style={{ display:'flex', justifyContent:'space-between', gap:12, alignItems:'center' }}><label style={{ color:theme.textMute, fontSize:10 }}><input type="checkbox" checked={usePricingMix} onChange={event => setUsePricingMix(event.target.checked)} /> Use weighted pricing mix in the 36-month projection · inputs preview live; Save commits a version</label><div style={{ display:'flex', gap:7 }}><button disabled={!!busy} onClick={recalibrate} style={button(theme)}>{busy === 'research' ? 'council researching…' : 'recalibrate with SOMA'}</button><button disabled={!!busy} onClick={save} style={{ ...button(theme), background:theme.ember, color:theme.voidDeep, borderColor:theme.ember }}>{busy === 'save' ? 'calculating…' : 'save + recalculate'}</button></div></div>
  </div>;
}

function Finance({ job, theme }) {
  const model = job?.financialModel;
  if (!model) return <div style={box(theme)}>No financial model is available yet.</div>;
  return <div style={{ display:'grid', gap:14 }}>
    <div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.18em', textTransform:'uppercase' }}>deterministic model</div><p style={{ color:theme.textDim, fontSize:11, lineHeight:1.6 }}>{model.methodology}</p>{model.warnings?.map(item => <div key={item} style={{ color:'oklch(0.78 0.1 60)', fontSize:11, marginTop:6 }}>⚠ {item}</div>)}</div>
    <div style={{ display:'grid', gridTemplateColumns:'repeat(3,minmax(0,1fr))', gap:10 }}>{Object.entries(model.scenarios || {}).map(([name, scenario]) => <div key={name} style={box(theme)}><div style={{ color:theme.ember, fontSize:10, textTransform:'uppercase' }}>{name}</div>{scenario.annual.map(year => <div key={year.year} style={{ marginTop:10, color:theme.textDim, fontSize:11 }}>Year {year.year}: {cash(year.revenue)} revenue</div>)}<div style={{ marginTop:12, color:theme.text, fontSize:11 }}>Break-even: {scenario.breakEvenMonth ? `month ${scenario.breakEvenMonth}` : 'not within 36 months'}</div><div style={{ marginTop:5, color:theme.text, fontSize:11 }}>Ending cash: {cash(scenario.endingCash)}</div></div>)}</div>
    <div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, textTransform:'uppercase', marginBottom:12 }}>price × volume sensitivity · monthly operating profit</div><div style={{ display:'grid', gridTemplateColumns:'repeat(3,minmax(0,1fr))', gap:7 }}>{(job.sensitivityAnalysis?.cells || []).map(cell => <div key={`${cell.priceFactor}-${cell.volumeFactor}`} style={{ padding:10, border:`1px solid ${theme.hair}`, color:cell.monthlyOperatingProfit >= 0 ? 'oklch(0.74 0.10 145)' : 'oklch(0.74 0.10 25)', fontSize:10 }}>{Math.round(cell.priceFactor*100)}% price · {Math.round(cell.volumeFactor*100)}% volume<br /><strong>{cash(cell.monthlyOperatingProfit)}</strong></div>)}</div></div>
  </div>;
}

function Evidence({ job, theme }) {
  const evidence = job?.evidence || {};
  return <div style={{ display:'grid', gap:10 }}>
    <div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.18em', textTransform:'uppercase' }}>research ledger · {evidence.status?.replaceAll('_', ' ')}</div><p style={{ color:theme.textMute, fontSize:11, lineHeight:1.6 }}>{evidence.disclaimer}</p></div>
    {(evidence.sources || []).map(source => <a key={source.id || source.url} href={source.url} target="_blank" rel="noreferrer" style={{ ...box(theme), display:'block', textDecoration:'none' }}><div style={{ color:source.authoritative ? theme.ember : theme.textMute, fontSize:9, textTransform:'uppercase', letterSpacing:'.14em' }}>{source.id} · {source.category} · {source.authoritative ? 'authoritative' : source.provider}</div><div style={{ marginTop:7, color:theme.text, fontSize:12 }}>{source.title}</div><div style={{ marginTop:6, color:theme.textDim, fontSize:10, lineHeight:1.5 }}>{source.excerpt}</div><div style={{ marginTop:7, color:theme.textMute, fontSize:9 }}>{source.url}</div></a>)}
    {!evidence.sources?.length && <div style={box(theme)}>No live sources were returned. SOMA has marked market claims as hypotheses.</div>}
  </div>;
}

function Operations({ job, setJob, theme, onError }) {
  const workspace = job?.operatingWorkspace || {};
  const update = async (collection, entry, patch) => { try { const result = await somaBackend.updateBusinessPlanOperations(job.id, { collection, id:entry.id, patch }); setJob(current => ({ ...current, operatingWorkspace:result.operatingWorkspace })); } catch (error) { onError(error.message); } };
  return <div style={{ display:'grid', gridTemplateColumns:'repeat(2,minmax(0,1fr))', gap:12 }}>{Object.entries(workspace).filter(([,value]) => Array.isArray(value)).map(([collection, entries]) => <section key={collection} style={box(theme)}><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.17em', textTransform:'uppercase', marginBottom:12 }}>{collection}</div>{entries.map(entry => <div key={entry.id} style={{ padding:'10px 0', borderTop:`1px solid ${theme.hair}` }}><div style={{ color:theme.text, fontSize:11, lineHeight:1.5 }}>{entry.title}</div><div style={{ display:'flex', justifyContent:'space-between', gap:8, marginTop:7, color:theme.textMute, fontSize:9 }}><span>{entry.owner}{entry.due ? ` · ${entry.due}` : ''}</span><select value={entry.status} onChange={event => update(collection, entry, { status:event.target.value })} style={{ background:'transparent', border:`1px solid ${theme.hair}`, color:theme.textDim, fontSize:9 }}><option value="open">open</option><option value="in_progress">in progress</option><option value="validated">validated</option><option value="done">done</option><option value="rejected">rejected</option></select></div></div>)}</section>)}</div>;
}

function Scenarios({ job, setJob, theme, onError }) {
  const [capital, setCapital] = useState(job?.financialModel?.assumptions?.startingCapital || 5000);
  const [years, setYears] = useState(3);
  const [busy, setBusy] = useState(false);
  const create = async () => { setBusy(true); try { const result = await somaBackend.createBusinessPlanScenario(job.id, { name:`${years}-year · ${cash(capital)} capital`, question:`What would the business look like over ${years} years with ${cash(capital)} starting capital?`, assumptions:{ startingCapital:Number(capital) } }); setJob(current => ({ ...current, scenarios:[...(current.scenarios || []), result.scenario] })); } catch (error) { onError(error.message); } finally { setBusy(false); } };
  return <div style={{ display:'grid', gap:12 }}><div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, letterSpacing:'.17em', textTransform:'uppercase' }}>branch a scenario</div><div style={{ display:'flex', gap:10, alignItems:'end', marginTop:14 }}><label style={{ color:theme.textMute, fontSize:9 }}>STARTING CAPITAL<input type="number" value={capital} onChange={e => setCapital(e.target.value)} style={{ display:'block', marginTop:5, padding:8, background:'transparent', border:`1px solid ${theme.hair}`, color:theme.text }} /></label><label style={{ color:theme.textMute, fontSize:9 }}>HORIZON<select value={years} onChange={e => setYears(e.target.value)} style={{ display:'block', marginTop:5, padding:8, background:'oklch(0.12 0.01 50)', border:`1px solid ${theme.hair}`, color:theme.text }}><option value="1">1 year</option><option value="3">3 years</option></select></label><button disabled={busy} onClick={create} style={button(theme)}>{busy ? 'calculating…' : 'create branch'}</button></div></div>{(job.scenarios || []).map(scenario => <div key={scenario.id} style={box(theme)}><div style={{ color:theme.text, fontSize:12 }}>{scenario.name}</div><div style={{ marginTop:6, color:theme.textMute, fontSize:10 }}>{scenario.question}</div><div style={{ marginTop:10, color:theme.ember, fontSize:11 }}>Base year 3 revenue: {cash(scenario.financialModel?.scenarios?.base?.annual?.[2]?.revenue)} · ending cash {cash(scenario.financialModel?.scenarios?.base?.endingCash)}</div></div>)}</div>;
}

function History({ job, setJob, theme, onError }) {
  const [history, setHistory] = useState(null); const [diff, setDiff] = useState(null);
  useEffect(() => { somaBackend.getBusinessPlanVersions(job.id).then(setHistory).catch(error => onError(error.message)); }, [job.id]);
  const compare = async version => { try { const result = await somaBackend.getBusinessPlanVersionDiff(job.id, version); setDiff(result.diff); } catch (error) { onError(error.message); } };
  const restore = async version => { if (!window.confirm(`Restore version ${version}? The current plan will be preserved.`)) return; try { const result = await somaBackend.restoreBusinessPlanVersion(job.id, version); setJob(result.job); setDiff(null); setHistory(await somaBackend.getBusinessPlanVersions(job.id)); } catch (error) { onError(error.message); } };
  return <div style={{ display:'grid', gridTemplateColumns:'minmax(0,1fr) minmax(280px,.7fr)', gap:12 }}><div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, textTransform:'uppercase' }}>version history</div>{(history?.versions || []).map(version => <div key={version.id || version.version} style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'12px 0', borderBottom:`1px solid ${theme.hair}` }}><div><div style={{ color:theme.text, fontSize:11 }}>Version {version.version}</div><div style={{ color:theme.textMute, fontSize:9 }}>{version.reason}</div></div><div style={{ display:'flex', gap:6 }}><button onClick={() => compare(version.version)} style={button(theme)}>diff</button><button onClick={() => restore(version.version)} style={button(theme)}>restore</button></div></div>)}<div style={{ paddingTop:12, color:theme.textDim, fontSize:11 }}>Current version {history?.currentVersion || job.currentVersion}</div></div><div style={box(theme)}><div style={{ color:theme.ember, fontSize:10, textTransform:'uppercase' }}>difference</div>{diff ? <><p style={{ color:theme.textDim, fontSize:11 }}>+{diff.addedCount} added · −{diff.removedCount} removed lines</p>{diff.added.slice(0,8).map(line => <div key={`a-${line}`} style={{ color:'oklch(0.72 0.10 145)', fontSize:9, marginTop:5 }}>+ {line}</div>)}{diff.removed.slice(0,8).map(line => <div key={`r-${line}`} style={{ color:'oklch(0.72 0.10 25)', fontSize:9, marginTop:5 }}>− {line}</div>)}</> : <p style={{ color:theme.textMute, fontSize:11 }}>Choose a saved version to compare it with the current plan.</p>}</div></div>;
}

export default function BusinessWorkspacePanels({ tab, job, setJob, theme, onError }) {
  if (tab === 'market') return <MarketModel job={job} setJob={setJob} theme={theme} onError={onError} />;
  if (tab === 'finance') return <Finance job={job} theme={theme} />;
  if (tab === 'evidence') return <Evidence job={job} theme={theme} />;
  if (tab === 'operate') return <Operations job={job} setJob={setJob} theme={theme} onError={onError} />;
  if (tab === 'scenarios') return <Scenarios job={job} setJob={setJob} theme={theme} onError={onError} />;
  return <History job={job} setJob={setJob} theme={theme} onError={onError} />;
}
