/**
 * core/SignalSchema.cjs
 * 
 * Standardized vocabulary for SOMA Cognitive Operating System.
 * Defines valid signal types and their required payloads.
 */

const SignalDefinitions = {
    // ── Repository Signals ──
    'repo.file.changed': {
        description: 'Emitted when a file is modified',
        required: ['path', 'filename']
    },
    'repo.file.added': {
        description: 'Emitted when a new file is created',
        required: ['path', 'filename']
    },
    'repo.batch.change': {
        description: 'Compressed signal representing multiple file changes',
        required: ['files', 'actions']
    },

    // ── Health & Diagnostics ──
    'health.metrics': {
        description: 'Periodic system resource metrics',
        required: ['cpuUsage', 'ramUsage', 'dbSizeGB']
    },
    'health.warning': {
        description: 'Critical system health alerts',
        required: ['issue', 'details']
    },
    'system.resource.critical': {
        description: 'Critical resource pressure requiring throttling or memory relief',
        required: ['issue']
    },
    'system.policy.actions': {
        description: 'Policy engine actions recommended for current system state',
        required: ['actions']
    },

    // ── Swarm & Engineering ──
    'swarm.experience': {
        description: 'Log of an autonomous engineering loop',
        required: ['sessionId', 'filepath', 'success']
    },
    'swarm.optimization.needed': {
        description: 'Signalled when swarm performance drops below threshold',
        required: ['successRate', 'totalRuns']
    },
    'swarm.discovery.ideas': {
        description: 'New capability ideas generated by the discovery swarm',
        required: ['ideas']
    },
    'swarm.health.report': {
        description: 'Periodic aggregate health report emitted by the engineering swarm',
        required: []
    },

    // ── Goals & Insights ──
    'goal.created': {
        description: 'Emitted when a new goal is created by any source',
        required: ['goalId', 'title', 'category', 'source', 'priority']
    },
    'insight.generated': {
        description: 'Emitted when a thought synthesis or reasoning produces a new insight',
        required: ['insight', 'source']
    },
    'memory.stored': {
        description: 'Emitted when MnemonicArbiter stores a new memory',
        required: ['memoryId', 'importance', 'source']
    },
    'memory.spine.synced': {
        description: 'Emitted when MemorySpine rebuilds and syncs into ThoughtNetwork',
        required: ['status', 'nodes', 'indexed']
    },

    // ── Diagnostics & Experiments ──
    'diagnostic.anomaly': {
        description: 'Emitted when an anomaly is detected in system health or behavior',
        required: ['component', 'issue', 'severity']
    },
    'experiment.result': {
        description: 'Emitted when a discovery swarm experiment completes',
        required: ['experimentId', 'success', 'filepath']
    },

    // ── Capability Health ──
    'capability.map.updated': {
        description: 'Full side-effect-free capability health map',
        required: ['capabilities', 'timestamp']
    },
    'capability.degraded': {
        description: 'A capability probe changed from healthy to degraded',
        required: ['capability']
    },
    'capability.restored': {
        description: 'A capability probe changed from degraded to healthy',
        required: ['capability']
    },

    // ── UI & User ──
    'ui.navigate': {
        description: 'Emitted when the user changes dashboard modules',
        required: ['module']
    },
    'user.interaction': {
        description: 'Direct user input through chat or orb',
        required: ['text', 'mode']
    },
    'vision.channel_requested': {
        description: 'Requests vision daemon to switch its capture channel',
        required: ['channel']
    },
    'vision.delta': {
        description: 'Lightweight visual heartbeat emitted when full vision analysis is unavailable',
        required: ['channel', 'imagePath', 'timestamp']
    },
    'vision.perceived': {
        description: 'Vision daemon completed an object/perception analysis pass',
        required: ['channel', 'imagePath', 'analysis', 'timestamp']
    },

    // ── Knowledge Library (Lobe Training Dataset) ──
    'knowledge.filed': {
        description: 'Emitted when KnowledgeCuratorArbiter writes a new MD entry to a lobe library',
        required: ['lobe', 'type', 'filepath', 'count']
    },
    'training.threshold.approaching': {
        description: 'Emitted when a lobe knowledge library reaches 75% of the training threshold',
        required: ['lobe', 'count', 'threshold', 'remaining']
    },
    'training.threshold.ready': {
        description: 'Emitted when a lobe knowledge library hits 100 entries and is ready for LoRA fine-tuning',
        required: ['lobe', 'count', 'knowledgeDir', 'message']
    }
};

class SignalRegistry {
    constructor() {
        this.definitions = new Map(Object.entries(SignalDefinitions));
    }

    validate(signal) {
        if (!signal || !signal.type) return true;
        
        const def = this.definitions.get(signal.type);
        if (!def) {
            console.warn(`[SignalRegistry] Unknown signal type: ${signal.type}`);
            return true; // Allow unknown signals for now but warn
        }

        for (const field of def.required) {
            if (!signal.payload || signal.payload[field] === undefined) {
                throw new Error(`Missing required field '${field}' for signal type '${signal.type}'`);
            }
        }

        return true;
    }
}

module.exports = {
    SignalDefinitions,
    SignalRegistry,
    default: new SignalRegistry()
};
