/**
 * TrinityStatusGenerator.js
 *
 * Auto-generates TRINITY_STATUS.md showing current system state
 */

import fs from 'fs/promises';
import path from 'path';

export class TrinityStatusGenerator {
    constructor(system) {
        this.system = system;
    }

    async generateStatusReport() {
        const timestamp = new Date().toISOString();
        const uptime = process.uptime();
        const allComponents = Object.keys(this.system).filter(k => !k.startsWith('_'));

        const markdown = `# 🔱 SOMA Trinity Status Report

**Generated:** ${timestamp}
**Uptime:** ${Math.floor(uptime / 60)} minutes ${Math.floor(uptime % 60)} seconds
**Components Loaded:** ${allComponents.length}

---

## 🧠 Neural Lobe Distribution

### COGNITIVE (The Brain)
${this._getLobeStatus('COGNITIVE')}

### EXECUTIVE (The Hands)
${this._getLobeStatus('EXECUTIVE')}

### KNOWLEDGE (The Memory)
${this._getLobeStatus('KNOWLEDGE')}

### LIMBIC (The Heart)
${this._getLobeStatus('LIMBIC')}

### EXTERNAL (The Senses)
${this._getLobeStatus('EXTERNAL')}

---

## 🔱 Trinity Pillars

### Pillar 1: Instinct (GEMMA-3)
${this._getPillarStatus('instinct', {
    localModelManager: 'Local Model Manager (gemma3:4b)',
    autoTrainingCoordinator: 'Auto Training Coordinator',
    ollamaAutoTrainer: 'Ollama Auto-Trainer'
})}

### Pillar 2: Knowledge (Fractals/ThoughtNetwork)
${this._getPillarStatus('knowledge', {
    thoughtNetwork: 'Thought Network',
    mnemonic: 'Mnemonic Memory',
    hippocampus: 'Hippocampus (Memory Cortex)',
    knowledgeGraph: 'Knowledge Graph Fusion',
    fragmentRegistry: 'Fragment Registry'
})}
- **Active Fragments:** ${this.system.fragmentRegistry?.stats?.activeFragments || 0} (Indexed as Virtual Arbiters)

### Pillar 3: Causality (Crona/Temporal)
${this._getPillarStatus('causality', {
    crona: 'Crona Arbiter (The Governor)',
    worldModel: 'World Model (Imagination)',
    causality: 'Causality Arbiter',
    timekeeper: 'Timekeeper Arbiter',
    merovingian: 'Merovingian Cortex'
})}

---

## 🧠 Core Internal Organs

${this._getComponentStatus('quadBrain', '**QuadBrain** (4-Perspective Reasoning)')}
${this._getComponentStatus('messageBroker', '**MessageBroker** (Nervous System)')}
${this._getComponentStatus('emotional', '**Emotional Engine** (The Pulse)')}
${this._getComponentStatus('beliefSystem', '**Belief System** (The Spine)')}
${this._getComponentStatus('selfModel', '**Recursive Self-Model**')}

---

## 🤖 Autonomous Systems

${this._getComponentStatus('selfImprovement', '**Self-Improvement Coordinator**')}
${this._getComponentStatus('codeObserver', '**Code Observation Arbiter**')}
${this._getComponentStatus('goalPlanner', '**Goal Planner Arbiter**')}
${this._getComponentStatus('curiosity', '**Curiosity Engine**')}
${this._getComponentStatus('noveltyTracker', '**Novelty Tracker**')}

---

## 📊 System Statistics

${this._getStats()}

---

## 🧬 All Loaded Components (${allComponents.length})

${allComponents.sort().map(name => `- ${name}`).join('\n')}

---

## 🏥 Health Status

${this._getHealthStatus()}

---

*This report is auto-generated by TrinityStatusGenerator.js on SOMA startup.*
*Last updated: ${timestamp}*
`;

        return markdown;
    }

    _getPillarStatus(pillar, components) {
        const status = [];
        for (const [key, label] of Object.entries(components)) {
            const exists = !!this.system[key];
            status.push(`- ${exists ? '✅' : '❌'} ${label}`);
        }
        return status.join('\n');
    }

    _getComponentStatus(key, label) {
        return `- ${this.system[key] ? '✅' : '❌'} ${label}`;
    }

    _getLobeStatus(lobe) {
        if (!this.system.messageBroker) return '- MessageBroker Offline';
        const arbiters = this.system.messageBroker.getArbitersByLobe(lobe);
        if (arbiters.length === 0) return '- No active organs';
        return arbiters.map(a => `- ✅ **${a.name}** (${a.classification || 'GENERALIST'})`).join('\n');
    }

    _getStats() {
        const stats = [];

        if (this.system.selfModel?.getCognitiveVelocity) {
            try {
                const velocity = this.system.selfModel.getCognitiveVelocity();
                stats.push(`- **Cognitive Velocity:** ${velocity.toFixed(1)}`);
            } catch (e) { /* ignore */ }
        }

        if (this.system.goalPlanner?.stats) {
            stats.push(`- **Goals Created:** ${this.system.goalPlanner.stats.goalsCreated || 0}`);
            stats.push(`- **Goals Active:** ${this.system.goalPlanner.activeGoals?.size || 0}`);
        }

        if (this.system.anomalyDetector?.stats) {
            stats.push(`- **Anomalies Detected:** ${this.system.anomalyDetector.stats.anomaliesDetected || 0}`);
        }

        if (this.system.localModelManager) {
            stats.push(`- **Current Model:** ${process.env.OLLAMA_MODEL || 'gemma3:4b'}`);
        }

        if (this.system.messageBroker?.arbiters) {
            stats.push(`- **Arbiters Registered:** ${this.system.messageBroker.arbiters.size}`);
        }

        return stats.length > 0 ? stats.join('\n') : '- No statistics available';
    }

    _getHealthStatus() {
        const health = [];

        // Check Trinity Pillars
        const instinct = !!(this.system.localModelManager);
        const knowledge = !!(this.system.thoughtNetwork || this.system.mnemonic);
        const causality = !!(this.system.crona || this.system.worldModel);

        const trinityHealth = instinct && knowledge && causality ? '✅ ALL PILLARS ACTIVE' : '⚠️ SOME PILLARS INACTIVE';
        health.push(`**Trinity:** ${trinityHealth}`);

        // Check Core Organs
        const coreActive = !!(this.system.quadBrain && this.system.messageBroker);
        health.push(`**Core Organs:** ${coreActive ? '✅ HEALTHY' : '⚠️ DEGRADED'}`);

        // Overall status
        const allComponents = Object.keys(this.system).filter(k => !k.startsWith('_')).length;
        health.push(`**Overall:** ${allComponents >= 50 ? '✅ FULLY OPERATIONAL' : allComponents >= 20 ? '⚠️ PARTIALLY OPERATIONAL' : '❌ DEGRADED'}`);

        return health.join('\n');
    }

    async saveToFile(outputPath = './TRINITY_STATUS.md') {
        try {
            const report = await this.generateStatusReport();
            await fs.writeFile(outputPath, report, 'utf-8');
            console.log(`✅ Trinity status report saved to ${outputPath}`);
            return outputPath;
        } catch (error) {
            console.error(`❌ Failed to save Trinity status: ${error.message}`);
            throw error;
        }
    }
}
