/**
 * server/finance/ReportGenerator.js
 *
 * Generates professional financial analysis reports from ExcelAnalyzer output.
 * Output formats: HTML (printable/emailable) and Markdown (chat-friendly).
 */

function fmtNum(n) {
    if (typeof n !== 'number') return String(n ?? '—');
    return n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

const SEVERITY_COLORS = {
    critical: '#dc2626',
    high:     '#ea580c',
    medium:   '#ca8a04',
    low:      '#16a34a'
};

const SEVERITY_BADGE = {
    critical: '🔴 CRITICAL',
    high:     '🟠 HIGH',
    medium:   '🟡 MEDIUM',
    low:      '🟢 LOW'
};

export class ReportGenerator {
    /**
     * Generate a Markdown report suitable for SOMA chat output.
     * @param {object} analysis - result from ExcelAnalyzer.analyze()
     * @param {object} opts
     * @param {string} opts.filename - original filename
     * @param {string} opts.preparedFor - e.g. "Sisterson Financial Group"
     * @returns {string}
     */
    toMarkdown(analysis, opts = {}) {
        const { filename = 'Workbook', preparedFor = '' } = opts;
        const now = new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' });
        const lines = [];

        lines.push(`## Financial Analysis Report`);
        lines.push(`**File:** ${filename}${preparedFor ? `  |  **Prepared for:** ${preparedFor}` : ''}`);
        lines.push(`**Generated:** ${now}`);
        lines.push('');

        if (!analysis.ok) {
            lines.push(`> ⚠️ **Analysis failed:** ${analysis.error}`);
            return lines.join('\n');
        }

        // Executive summary
        lines.push('### Executive Summary');
        lines.push(`Analyzed **${analysis.sheetCount}** sheet(s) | **${analysis.totalFindings}** finding(s) — ${analysis.criticalCount} critical, ${analysis.highCount} high`);
        lines.push('');
        if (analysis.summary) {
            lines.push(analysis.summary);
            lines.push('');
        }

        if (analysis.totalFindings === 0) {
            lines.push('✅ No issues detected. The workbook appears to be structurally sound.');
            lines.push('');
            lines.push('---');
            lines.push('*This report is generated by automated analysis. Always verify findings manually before taking action.*');
            return lines.join('\n');
        }

        // Per-sheet findings
        for (const sheet of analysis.sheets) {
            if (sheet.findings.length === 0) continue;
            lines.push(`---`);
            lines.push(`### Sheet: ${sheet.sheetName}`);
            lines.push(`${sheet.findings.length} finding(s) across ${sheet.cellCount} cells analyzed`);
            lines.push('');

            for (const f of sheet.findings) {
                const badge = SEVERITY_BADGE[f.severity] || f.severity.toUpperCase();
                lines.push(`**${badge}** — \`${f.cell}\``);
                lines.push(f.message);

                if (f.type === 'sum_discrepancy') {
                    lines.push(`> Cached: **${fmtNum(f.cachedValue)}** | Re-computed: **${fmtNum(f.recomputedValue)}** | Delta: **${fmtNum(f.delta)}**`);
                    lines.push(`> Formula: \`=${f.formula}\``);
                }
                if (f.type === 'sum_range_gap' && f.gap) {
                    lines.push(`> Missing cell: \`${f.gap.cell}\` = ${fmtNum(f.gap.value)}`);
                    lines.push(`> Current formula: \`=${f.formula}\``);
                }
                if (f.type === 'formula_error') {
                    lines.push(`> Error: \`${f.value}\`${f.formula ? `  |  Formula: \`=${f.formula}\`` : ''}`);
                }
                if (f.type === 'outlier') {
                    lines.push(`> Value: ${fmtNum(f.value)} | Column mean: ${fmtNum(f.mean)} | Z-score: ${f.zScore}σ`);
                }
                lines.push('');
            }
        }

        lines.push('---');
        lines.push('*This report is generated by automated analysis. All findings should be verified by a qualified professional before action is taken. Numbers reflect cached cell values at the time of analysis.*');
        return lines.join('\n');
    }

    /**
     * Generate a printable HTML report.
     * @param {object} analysis - result from ExcelAnalyzer.analyze()
     * @param {object} opts
     * @returns {string} full HTML document
     */
    toHTML(analysis, opts = {}) {
        const { filename = 'Workbook', preparedFor = '', preparedBy = 'SOMA Financial Analysis' } = opts;
        const now = new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' });

        const severityRow = (f) => {
            const color = SEVERITY_COLORS[f.severity] || '#6b7280';
            let detail = '';
            if (f.type === 'sum_discrepancy') {
                detail = `Cached: <strong>${fmtNum(f.cachedValue)}</strong> &nbsp;|&nbsp; Re-computed: <strong>${fmtNum(f.recomputedValue)}</strong> &nbsp;|&nbsp; Variance: <strong style="color:${color}">${fmtNum(f.delta)}</strong><br><code>=${escHtml(f.formula)}</code>`;
            } else if (f.type === 'sum_range_gap' && f.gap) {
                detail = `Excluded cell: <code>${f.gap.cell}</code> = ${fmtNum(f.gap.value)}<br>Formula: <code>=${escHtml(f.formula)}</code>`;
            } else if (f.type === 'formula_error') {
                detail = `Error: <code>${f.value}</code>${f.formula ? `<br>Formula: <code>=${escHtml(f.formula)}</code>` : ''}`;
            } else if (f.type === 'outlier') {
                detail = `Value: ${fmtNum(f.value)} &nbsp;|&nbsp; Column mean: ${fmtNum(f.mean)} &nbsp;|&nbsp; Z-score: ${f.zScore}σ`;
            } else if (f.type === 'hardcoded_constant') {
                detail = `Constants: ${f.constants.join(', ')}<br>Formula: <code>=${escHtml(f.formula)}</code>`;
            }
            return `
            <tr>
                <td style="color:${color};font-weight:700;white-space:nowrap">${f.severity.toUpperCase()}</td>
                <td><code>${f.cell}</code></td>
                <td>${escHtml(f.message)}</td>
                <td>${detail}</td>
            </tr>`;
        };

        const sheetSections = analysis.sheets?.filter(s => s.findings.length > 0).map(sheet => `
            <div class="sheet-section">
                <h3>${escHtml(sheet.sheetName)}</h3>
                <p class="meta">${sheet.findings.length} finding(s) &nbsp;·&nbsp; ${sheet.cellCount} cells analyzed</p>
                <table>
                    <thead><tr><th>Severity</th><th>Cell</th><th>Description</th><th>Detail</th></tr></thead>
                    <tbody>${sheet.findings.map(severityRow).join('')}</tbody>
                </table>
            </div>
        `).join('') || '';

        return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Financial Analysis Report — ${escHtml(filename)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; font-size: 13px; color: #1a1a1a; background: #fff; padding: 40px; }
  .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 20px; color: #1e3a5f; margin-bottom: 4px; }
  .header .meta { color: #6b7280; font-size: 12px; }
  .summary-box { background: #f8f9fa; border: 1px solid #e5e7eb; border-radius: 6px; padding: 16px; margin-bottom: 24px; }
  .summary-box h2 { font-size: 14px; color: #374151; margin-bottom: 8px; }
  .stat-row { display: flex; gap: 24px; margin-top: 8px; }
  .stat { text-align: center; }
  .stat .num { font-size: 28px; font-weight: 700; }
  .stat .label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
  .critical .num { color: #dc2626; }
  .high .num { color: #ea580c; }
  .total .num { color: #1e3a5f; }
  .sheet-section { margin-bottom: 32px; }
  .sheet-section h3 { font-size: 15px; color: #1e3a5f; border-left: 4px solid #1e3a5f; padding-left: 10px; margin-bottom: 6px; }
  .sheet-section .meta { color: #9ca3af; font-size: 11px; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #1e3a5f; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
  td { padding: 8px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
  tr:hover td { background: #f9fafb; }
  code { background: #f3f4f6; padding: 1px 5px; border-radius: 3px; font-size: 11px; word-break: break-all; }
  .disclaimer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 11px; font-style: italic; }
  .ok-banner { background: #d1fae5; border: 1px solid #6ee7b7; border-radius: 6px; padding: 16px; color: #065f46; font-weight: 600; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <h1>Financial Analysis Report</h1>
  <div class="meta">
    <strong>File:</strong> ${escHtml(filename)}
    ${preparedFor ? `&nbsp;·&nbsp; <strong>Prepared for:</strong> ${escHtml(preparedFor)}` : ''}
    &nbsp;·&nbsp; <strong>Prepared by:</strong> ${escHtml(preparedBy)}
    &nbsp;·&nbsp; ${now}
  </div>
</div>

<div class="summary-box">
  <h2>Executive Summary</h2>
  ${analysis.ok ? `
  <div class="stat-row">
    <div class="stat total"><div class="num">${analysis.totalFindings}</div><div class="label">Total Findings</div></div>
    <div class="stat critical"><div class="num">${analysis.criticalCount}</div><div class="label">Critical</div></div>
    <div class="stat high"><div class="num">${analysis.highCount}</div><div class="label">High</div></div>
    <div class="stat"><div class="num" style="color:#374151">${analysis.sheetCount}</div><div class="label">Sheets</div></div>
  </div>
  ${analysis.summary ? `<p style="margin-top:12px;color:#374151">${escHtml(analysis.summary).replace(/\n/g, '<br>')}</p>` : ''}
  ` : `<div style="color:#dc2626">Analysis failed: ${escHtml(analysis.error)}</div>`}
</div>

${analysis.ok && analysis.totalFindings === 0 ? '<div class="ok-banner">✅ No issues detected. The workbook appears to be structurally sound.</div>' : sheetSections}

<div class="disclaimer">
  This report is generated by automated analysis. All findings should be verified by a qualified professional before any action is taken.
  Numbers reflect cached cell values at the time of analysis. This report does not constitute professional accounting, tax, or legal advice.
</div>
</body>
</html>`;
    }
}

function escHtml(str) {
    return String(str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export default ReportGenerator;
